swagger: "2.0"
info:
  description: "SwordHealth Challenge"
  version: "1.0.0"
  title: "swordhealth"
basePath: "/api/v1"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: "users"
    description: "user entrypoint"
  - name: "tasks"
    description: "task entrypoint"
  - name: "authentication"
    description: "authentication entrypoint"
definitions:
  UpdateTask:
    type: "object"
    required:
      - "id"
    properties:
      id:
        type: "number"
      name:
        type: "string"
      summary:
        type: "string"
      perfomed_task_date:
        type: "string"
  Task:
    type: "object"
    required:
      - "id"
      - "user_id"
      - "name"
      - "summary"
      - "perfomed_task_date"
      - "created_at"
      - "updated_at"
    properties:
      id:
        type: "number"
      user_id:
        type: "number"
      name:
        type: "string"
      summary:
        type: "string"
      perfomed_task_date:
        type: "string"
      created_at:
        type: "string"
      updated_at:
        type: "string"
  TasksGetResponse:
    type: "object"
    required:
      - "tasks"
    properties:
      tasks:
        type: "array"
        items:
          $ref: "#/definitions/Task"
  CreateTask:
    type: "object"
    required:
      - "name"
      - "summary"
    properties:
      name:
        type: "string"
      summary:
        type: "string"
  User:
    type: "object"
    required:
      - "email"
      - "name"
      - "role"
      - "password"
    properties:
      email:
        type: "string"
      name: 
        type: "string"
      role:
        type: "string"
        description: "User role"
        enum:
          - "manager"
          - "technician"
      password:
        type: "string"
  Credential:
    type: "object"
    properties: 
      token:
        type: "string"
  Validation:
    type: "object"  
    properties: 
      message:
        type: "string"
      path:
        type: "array"
        items:
          type: "string"
      type:
        type: "string"
      context:
        type: "object"
        properties:
          limit:
            type: "number"
          value: 
            type: "string"
          label:
            type: "string"
          key:
            type: "string"
  BadRequest:
    type: "object"
    properties:
      details:
        type: "array"
        items:
          $ref: "#/definitions/Validation"
  DefaultResponse:
    type: "object"
    properties:
      message:
        type: "string"
paths:
  /health:
    get:
      tags:
        - 'others'
      x-swagger-router-controller: app
      summary: healthcheck
      operationId: isHealthly
      responses:
        204:
          description: yes, it is.
  /user:
    post:
      tags:
        - 'users'
      x-swagger-router-controller: app
      summary: create one user
      operationId: createUser
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: user has been created
          schema:
            $ref: "#/definitions/DefaultResponse"
        400:
          description: BadRequest
          schema:
            $ref: "#/definitions/BadRequest"
        409:
          description: Conflict
          schema:
            $ref: "#/definitions/DefaultResponse"
        500:
          description: internalError - UUID to search for logs
          schema:
            $ref: "#/definitions/DefaultResponse"
  /login:
    get:
      tags:
        - 'authentication'
      x-swagger-router-controller: app
      summary: create one user
      operationId: loginUser
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "query"
        description: "The user email"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The user password "
        required: true
        type: "string"
      responses:
        200:
          description: "successful logged in"
          schema:
            $ref: "#/definitions/Credential"
        500:
          description: internalError - UUID to search for logs
          schema:
            $ref: "#/definitions/DefaultResponse"
  /tasks:
    post:
      tags:
        - 'tasks'
      x-swagger-router-controller: app
      summary: create one task
      operationId: createTask
      security:
        - Bearer: []
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "task object"
        required: true
        schema:
          $ref: "#/definitions/CreateTask"
      responses:
        201:
          description: task has been created
          schema:
            $ref: "#/definitions/DefaultResponse"
        400:
          description: BadRequest
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: internalError - UUID to search for logs
          schema:
            $ref: "#/definitions/DefaultResponse"
    get:
      tags:
        - 'tasks'
      x-swagger-router-controller: app
      summary: get many tasks
      operationId: getTasks
      security:
        - Bearer: []
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "limit data"
        type: "string"
      - name: "offset"
        in: "query"
        description: "page"
        type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/TasksGetResponse"
        500:
          description: internalError - UUID to search for logs
          schema:
            $ref: "#/definitions/DefaultResponse"
    put:
      tags:
        - 'tasks'
      x-swagger-router-controller: app
      summary: update one task
      operationId: updateTask
      security:
        - Bearer: []
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "task object"
        required: true
        schema:
          $ref: "#/definitions/UpdateTask"
      responses:
        204:
          description: task has been updated
          schema:
            $ref: "#/definitions/DefaultResponse"
        400:
          description: BadRequest
          schema:
            $ref: "#/definitions/DefaultResponse"
        500:
          description: internalError - UUID to search for logs
          schema:
            $ref: "#/definitions/DefaultResponse"
    delete:
      tags:
        - 'tasks'
      x-swagger-router-controller: app
      summary: delete one task
      operationId: deleteTask
      security:
        - Bearer: []
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "taskId"
        in: "query"
        description: "Task id to delete"
        required: true
        type: "integer"
      responses:
        204:
          description: task has been deleted
          schema:
            $ref: "#/definitions/DefaultResponse"
        500:
          description: internalError - UUID to search for logs
          schema:
            $ref: "#/definitions/DefaultResponse"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: Bearer token
