FROM nginx:stable-alpine

RUN chown -R nginx:nginx /var/cache/nginx;

USER nginx
COPY --chown=nginx:nginx .conf/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --chown=nginx:nginx .conf/nginx/nginx.conf /etc/nginx/nginx.conf